---
title: "Mini-Project 2"
author: "Yi Wang & Ziwei 'Crystal' Zang"
date: "March 24, 2017"
output: html_document
---


## Loading the data


```{r, include=FALSE}
load("house_elections.rda")
load("candidates.rda")
load("committees.rda")
load("contributions.rda")
```

```{r}
library(dplyr)
library(ggplot2)
```

## function, join, 5 verbs,  Issues tab, blog post text

##Rename
```{r}
committees_copy <- committees%>%
  rename(cand_pcc = cmte_id)
```

##Contribution
```{r}
transaction_cand <- contributions%>%
  group_by(cand_id)%>%
  summarize(N = n(), transaction_amountsum = sum(transaction_amt))
  
```

##Join each candidate id with its corresponding contribution committees
```{r}
house_win<-house_elections%>%
  #Only looking at the candidates win the house election
  filter(ge_winner=="W")%>%
  rename(cand_id = fec_id)%>%
  #Looking at the detail information of each candidate
  left_join(candidates, by = "cand_id")%>%
  left_join(committees_copy, by = "cand_pcc")%>%
  rename(cand_id = cand_id.x)%>%
  left_join(transaction_cand, by = "cand_id")%>%
  select(cand_id,candidate_name,party, general_votes, cand_election_yr,cand_office_state, cand_pcc, cmte_name, transaction_amountsum)
```

```{r}
contributions%>%
  group_by(cand_id)%>%
  summarise(sum=sum(transaction_amt))
```

##Function for transaction amount for winning house candidates per states
```{r}
transaction_per_state <- function(state_arg){
  house_win%>%
    select(cand_office_state, transaction_amountsum)%>%
    group_by(cand_office_state)%>%
    summarise(transactionsum = sum(transaction_amountsum))%>%
    filter(cand_office_state == state_arg)
}
##Transaction Sum for State MA's and VA's winning house candidates, by running this function, the transaction sum for each state without writing repeatative commands
transaction_per_state(state_arg = "MA")
transaction_per_state(state_arg = "VA")
```





